import Foundation

extension TokenAccountSupportCatalog {
    static let supportByProvider: [UsageProvider: TokenAccountSupport] = [
        .openai: TokenAccountSupport(
            title: "API keys",
            subtitle: "Store multiple OpenAI API keys.",
            placeholder: "sk-...",
            injection: .environment(key: OpenAIAPISettingsReader.apiKeyEnvironmentKey),
            requiresManualCookieSource: false,
            cookieName: nil),
        .claude: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存 Claude sessionKey Cookie 或 OAuth access token。",
            placeholder: "粘贴 sessionKey 或 OAuth token…",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: "sessionKey"),
        .deepseek: TokenAccountSupport(
            title: "API tokens",
            subtitle: "Store multiple DeepSeek API keys.",
            placeholder: "Paste API key…",
            injection: .environment(key: DeepSeekSettingsReader.apiKeyEnvironmentKey),
            requiresManualCookieSource: false,
            cookieName: nil),
        .zai: TokenAccountSupport(
            title: "API token",
            subtitle: "保存在 CodexBar 配置文件中。",
            placeholder: "粘贴 token…",
            injection: .environment(key: ZaiSettingsReader.apiTokenKey),
            requiresManualCookieSource: false,
            cookieName: nil),
        .qwen: TokenAccountSupport(
            title: "API token",
            subtitle: "保存在 CodexBar 配置文件中。",
            placeholder: "粘贴 token…",
            injection: .environment(key: QwenSettingsReader.apiKeyEnvironmentKeys.first ?? "DASHSCOPE_API_KEY"),
            requiresManualCookieSource: false,
            cookieName: nil),
        .cursor: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 Cursor Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .opencode: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 OpenCode Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .opencodego: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 OpenCode Go Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .factory: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 Factory Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .minimax: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 MiniMax Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .manus: TokenAccountSupport(
            title: "Session tokens",
            subtitle: "Store multiple Manus session_id cookies.",
            placeholder: "session_id=…",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: "session_id"),
        .augment: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 Augment Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .ollama: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 Ollama Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .abacus: TokenAccountSupport(
            title: "会话 token",
            subtitle: "保存多个 Abacus AI Cookie header。",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .mistral: TokenAccountSupport(
            title: "Session tokens",
            subtitle: "Store multiple Mistral Cookie headers.",
            placeholder: "Cookie: …",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
        .copilot: TokenAccountSupport(
            title: "GitHub accounts",
            subtitle: "Sign in with multiple GitHub accounts via OAuth.",
            placeholder: "Paste GitHub token…",
            injection: .environment(key: "COPILOT_API_TOKEN"),
            requiresManualCookieSource: false,
            cookieName: nil),
        .venice: TokenAccountSupport(
            title: "API tokens",
            subtitle: "Store multiple Venice API keys.",
            placeholder: "Paste API key…",
            injection: .environment(key: VeniceSettingsReader.apiKeyEnvironmentKey),
            requiresManualCookieSource: false,
            cookieName: nil),
        .aigocode: TokenAccountSupport(
            title: "API token",
            subtitle: "Store multiple AigoCode API keys.",
            placeholder: "Paste API key…",
            injection: .environment(key: AigoCodeSettingsReader.apiKeyEnvironmentKeys.first ?? "AIGOCODE_API_KEY"),
            requiresManualCookieSource: false,
            cookieName: nil),
        .zenmux: TokenAccountSupport(
            title: "API token",
            subtitle: "Store multiple Zenmux API keys.",
            placeholder: "Paste API key…",
            injection: .environment(key: ZenmuxSettingsReader.apiKeyEnvironmentKeys.first ?? "ZENMUX_API_KEY"),
            requiresManualCookieSource: false,
            cookieName: nil),
        .stepfun: TokenAccountSupport(
            title: "TokenPlan credentials",
            subtitle: "Store multiple StepFun Step Plan / TokenPlan credentials.",
            placeholder: "Paste TokenPlan credential…",
            injection: .cookieHeader,
            requiresManualCookieSource: true,
            cookieName: nil),
    ]
}
